# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob 
    steps:
    - bash: echo build 
  - job: secondJob 
    steps:
    - bash: second job build build
    - bash: echo $(pipelinevariable)  

- stage: QADeploy
  dependsOn: Build
  jobs:
  - job: QaDeployJob 
    steps:
    - bash: echo build 
- stage: DevDeploy
  variables:
    environment: Dev
  dependsOn: Build 
  jobs:
  - job: DevDeployJob 
    steps:
    - bash: echo build 
    
- stage: ProdDepoy
  dependsOn: 
  - DevDeploy
  - QADeploy  
  jobs:
  - job: ProdDeployJob 
    steps:
    - bash: echo Prod Deploy 


