# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
    - job : BuildJob
      steps : 
      - bash: echo java -version
  - stage: 
    jobs:
    - deployment: DevDeployJob
      strategy:
       runOnce:
         deploy:
           steps:
             - script: echo deploy to dev      
  - stage: 
    jobs:
    - deployment: QaDeployeJob 
      strategy:
       runOnce:
         deploy:
           steps:
             - script: echo deploy to qa
        
